id: PA2767344
initial_creation_type: input
source_metadata:
  title: Nubpa Rigdzin Drak
  language: bo
  description: 'Texts by Nubpa Rigdzin Drak (nub pa rig ''dzin grags), who was born
    in the thirteenth century:'
  volume:
    fc723b4ca5e240a190ae982fa1943988:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: null
created_at: '2022-03-01T01:02:54.164274'
last_modified_at: '2022-03-01T01:02:54.164276'
statistics:
  total_words: 656
  total_non_words: 53
quality:
  non_words_ratio: 0.08
